### ISSUE TITLE
overwriting existing cron jobs

### ISSUE THREAD

**Issue by Mortifer80** [aviadra/anti-ads-pack#1]
please change 
echo '0 0 \* \* \* root /jffs/dns/disable_adds.sh -m' > /tmp/crontab
to 
echo '0 0 \* \* \* root /jffs/dns/disable_adds.sh -m' >> /tmp/crontab

as your overwriting cron jobs and causing time based access restrictions to fail

**Comment by aviadra** [comment]
Thank you, i'm glad to have gotten a peer review.
I'm was more concerned with making sure "my" stuff would work then anything else on the system.
I've committed your suggested change.

**Comment by Mortifer80** [comment]
No problems ... Doing the same was bugging me I couldn't get both working together till I noticed that .. 

Btw love your script it's awesome 

Kind Regards
Nicholas Green
